`MUTUALFUND`
INSERT INTO MUTUALFUND values();

`CLOSINGPRICE`
INSERT INTO CLOSINGPRICE values();

`CUSTOMER`
INSERT INTO CUSTOMER values();

`ADMINISTRATOR`
INSERT INTO ADMINISTRATOR values();

`ALLOCATION`
INSERT INTO ALLOCATION values();

`PREFERS`
INSERT INTO PREFERS values();

`TRXLOG`
INSERT INTO TRXLOG values();

`OWNS`
INSERT INTO OWNS values();

`MUTUALDATE`
INSERT INTO MUTUALDATE values();